server{
    # Listen to port 443 by SSL(IPv4 && IPv6)
    listen 443 ssl;
    listen [::]:443 ssl;

    # Subject requirement
    server_name hacharka.42.fr;

    # Certificats SSL
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Subject requirement: TLS v1.2 et TLS v1.3 ONLY
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Configuration FastCGI in order to send  NGINX the .php file to the WordPress container
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }  

}